import pandas as pd


courses = {
    "count": 12,
    "courses": [
        {
            "car": "UGRD",
            "catalogNumber": "103",
            "classNumbers": [
                "30181",
                "7074",
                "13342",
                "13379",
                "12239",
                "10585",
                "30184",
                "27818",
                "11176",
                "4460",
                "12252",
                "12256",
                "12268",
                "12273",
                "12297",
                "35719",
                "5226",
                "5227",
                "5229",
            ],
            "courseDetails": {
                "attributes": [
                    "COLL (CASE) A&H Breadth of Inquiry credit",
                    "IUB GenEd A&H credit",
                ],
                "description": "Specific topics will vary by section and over time, but all versions of C103 will meet the objectives of the College of Arts and Sciences Critical Approaches curriculum. The curriculum is intended for freshmen and sophomores, who will learn how scholars from the arts and humanities Breadth of Inquiry area frame questions, propose answers, and assess the validity of competing approaches. Writing and related skills are stressed.",
                "typicallyOffered": "Spring, Summer, Fall",
            },
            "courseId": "085763",
            "courseOfferNumber": 1,
            "courseTopicId": 0,
            "effdt": 1367380800000,
            "inst": "IUBLA",
            "maxCredits": 3,
            "minCredits": 3,
            "scheduled": "",
            "scheduledTerms": [],
            "subject": "COLL-C",
            "title": "CRITICAL APPROACHES TO THE ARTS AND HUMANITIES",
        },
        {
            "car": "UGRD",
            "catalogNumber": "103",
            "classNumbers": ["13342"],
            "courseDetails": {
                "attributes": [
                    "COLL (CASE) A&H Breadth of Inquiry credit",
                    "IUB GenEd A&H credit",
                ],
                "description": "Specific topics will vary by section and over time, but all versions of C103 will meet the objectives of the College of Arts and Sciences Critical Approaches curriculum. The curriculum is intended for freshmen and sophomores, who will learn how scholars from the arts and humanities Breadth of Inquiry area frame questions, propose answers, and assess the validity of competing approaches. Writing and related skills are stressed.",
                "typicallyOffered": "Spring, Summer, Fall",
            },
            "courseId": "085763",
            "courseOfferNumber": 1,
            "courseTopicId": 2,
            "effdt": 1367380800000,
            "inst": "IUBLA",
            "maxCredits": 3,
            "minCredits": 3,
            "scheduled": "",
            "scheduledTerms": [],
            "subject": "COLL-C",
            "title": "THE SEMIOTICS OF ADVERTISING (CRITICAL APPROACHES TO THE ARTS AND HUMANITIES)",
        },
        {
            "car": "GRAD",
            "catalogNumber": "621",
            "classNumbers": ["4491", "5277"],
            "courseDetails": {
                "attributes": [],
                "description": "This course centers on concepts, cases, and practices of analyzing needs in organizations. The identification of needs is a starting point for organizational and instructional development activities. The process of conducting needs analysis has a greater impact on performance improvement by attending to the context in the organization.",
                "typicallyOffered": "Fall",
            },
            "courseId": "015804",
            "courseOfferNumber": 1,
            "courseTopicId": 0,
            "effdt": 1388552400000,
            "inst": "IUBLA",
            "maxCredits": 3,
            "minCredits": 3,
            "scheduled": "",
            "scheduledTerms": [],
            "subject": "EDUC-R",
            "title": "ANALYSIS FOR INSTRUCTION AND PERFORMANCE IMPROVEMENT",
        },
        {
            "car": "UGRD",
            "catalogNumber": "360",
            "classNumbers": [
                "12670",
                "14709",
                "14750",
                "14759",
                "15137",
                "14108",
                "14143",
                "14165",
                "13434",
                "14434",
                "36831",
                "31486",
                "34010",
                "33837",
                "34390",
                "36830",
                "31484",
                "34011",
                "35665",
                "33114",
                "33111",
                "33778",
                "33115",
                "12070",
                "12073",
                "14022",
                "11459",
                "13817",
                "14199",
                "11959",
                "14222",
                "14224",
                "13584",
                "11681",
                "31665",
                "35732",
                "35734",
            ],
            "courseDetails": {
                "attributes": [],
                "description": "Focuses on emerging trends in sports media, including related social and political issues, content creation and production, and special event coverage.",
                "typicallyOffered": "Spring, Fall",
            },
            "courseId": "097258",
            "courseOfferNumber": 1,
            "courseTopicId": 0,
            "effdt": 1735707600000,
            "inst": "IUBLA",
            "maxCredits": 4,
            "minCredits": 1,
            "scheduled": "",
            "scheduledTerms": [],
            "subject": "MSCH-B",
            "title": "SPORTS MEDIA TOPICS",
        },
        {
            "car": "UGRD",
            "catalogNumber": "360",
            "classNumbers": ["14750"],
            "courseDetails": {
                "attributes": [],
                "description": "Focuses on emerging trends in sports media, including related social and political issues, content creation and production, and special event coverage.",
                "typicallyOffered": "Spring, Fall",
            },
            "courseId": "097258",
            "courseOfferNumber": 1,
            "courseTopicId": 22,
            "effdt": 1735707600000,
            "inst": "IUBLA",
            "maxCredits": 4,
            "minCredits": 1,
            "scheduled": "",
            "scheduledTerms": [],
            "subject": "MSCH-B",
            "title": "COLLEGE SPORTS MEDIA STRATEGY (SPORTS MEDIA TOPICS)",
        },
        {
            "car": "UGRD",
            "catalogNumber": "360",
            "classNumbers": ["15137"],
            "courseDetails": {
                "attributes": [],
                "description": "Focuses on emerging trends in sports media, including related social and political issues, content creation and production, and special event coverage.",
                "typicallyOffered": "Spring, Fall",
            },
            "courseId": "097258",
            "courseOfferNumber": 1,
            "courseTopicId": 24,
            "effdt": 1735707600000,
            "inst": "IUBLA",
            "maxCredits": 4,
            "minCredits": 1,
            "scheduled": "",
            "scheduledTerms": [],
            "subject": "MSCH-B",
            "title": "LITTLE 500 DOCUMENTARY SERIES (SPORTS MEDIA TOPICS)",
        },
        {
            "car": "UGRD",
            "catalogNumber": "103",
            "classNumbers": ["15035", "13801"],
            "courseDetails": {
                "attributes": ["Class uses IU eTexts"],
                "description": "The primary focus of this course is medical terminology skills including spelling, pronunciation, analysis of root words, prefixes/suffixes, and the correct use of terms when writing or conversing.  Review commonly encountered laboratory, radiological, & tests associated with body systems.  Students will learn basic anatomy, physiology, and the medical terminology.  ",
                "typicallyOffered": "Spring, Fall",
            },
            "courseId": "098354",
            "courseOfferNumber": 1,
            "courseTopicId": 0,
            "effdt": 1722484800000,
            "inst": "IUBLA",
            "maxCredits": 3,
            "minCredits": 3,
            "scheduled": "",
            "scheduledTerms": [],
            "subject": "NURS-A",
            "title": "MEDICAL TERMINOLOGY FOR HEALTH PROFESSIONALS",
        },
        {
            "car": "UGRD",
            "catalogNumber": "355",
            "classNumbers": ["5135", "10562", "13197", "4134", "2619"],
            "courseDetails": {
                "attributes": [],
                "description": "Introduces nursing and other health science students to the basic concepts and techniques of data analysis needed in professional health care practice.  Principles of measurement, data summarization, and univariate and bivariate statistics are examined.  Differences in types of qualitative data and methods by which these types of data can be interpreted are also explored.  Emphasis is placed on the application of fundamental concepts to real world situations in client care.",
                "typicallyOffered": "Spring, Summer, Fall",
            },
            "courseId": "036022",
            "courseOfferNumber": 3,
            "courseTopicId": 0,
            "effdt": 1735707600000,
            "inst": "IUBLA",
            "maxCredits": 3,
            "minCredits": 3,
            "scheduled": "",
            "scheduledTerms": [],
            "subject": "NURS-H",
            "title": "DATA ANALYSIS FOR PRACTICE AND RESEARCH",
        },
        {
            "car": "UGRD",
            "catalogNumber": "160",
            "classNumbers": ["14494", "5020"],
            "courseDetails": {
                "attributes": [],
                "description": "Course addresses cardiopulmonary resuscitation (CPR), rescue breathing, choking, wounds, bleeding, burns, sudden illnesses, musculoskeletal injuries, and defibrillation/ the use of Automated External Defibrillators (AEDs). Skills are practiced in small lab settings.  Students have the opportunity to gain professional certification.",
                "typicallyOffered": "Spring, Fall",
            },
            "courseId": "087891",
            "courseOfferNumber": 1,
            "courseTopicId": 0,
            "effdt": 1525147200000,
            "inst": "IUBLA",
            "maxCredits": 3,
            "minCredits": 2,
            "scheduled": "",
            "scheduledTerms": [],
            "subject": "SPH-H",
            "title": "FIRST AID AND EMERGENCY CARE",
        },
        {
            "car": "UGRD",
            "catalogNumber": "290",
            "classNumbers": ["9751", "9752", "8826", "8827", "5138"],
            "courseDetails": {
                "attributes": [],
                "description": None,
                "typicallyOffered": "Spring, Summer, Fall",
            },
            "courseId": "087899",
            "courseOfferNumber": 1,
            "courseTopicId": 0,
            "effdt": 1596254400000,
            "inst": "IUBLA",
            "maxCredits": 3,
            "minCredits": 2,
            "scheduled": "",
            "scheduledTerms": [],
            "subject": "SPH-K",
            "title": "MOVMT EXP PRESCH & ELEM CHLD",
        },
        {
            "car": "GRAD",
            "catalogNumber": "520",
            "classNumbers": ["9844"],
            "courseDetails": {
                "attributes": [],
                "description": "This course covers theories and concepts related to research methods and data analysis in sport management. Specific focus will be given to action components of the research process including: design and formulation, research strategies, methodological tools, and data analytical methods necessary to perform research. ",
                "typicallyOffered": "Spring, Fall",
            },
            "courseId": "093230",
            "courseOfferNumber": 1,
            "courseTopicId": 0,
            "effdt": 1514782800000,
            "inst": "IUBLA",
            "maxCredits": 3,
            "minCredits": 3,
            "scheduled": "",
            "scheduledTerms": [],
            "subject": "SPH-M",
            "title": "RESEARCH METHODS IN SPORT MANAGEMENT",
        },
        {
            "car": "GRAD",
            "catalogNumber": "700",
            "classNumbers": ["13061"],
            "courseDetails": {
                "attributes": [],
                "description": "Research methods used in the nutritional sciences will be a focus.  Foundation topics in methodology will include hypothesis formation and testing, study design, sampling, randomization, comparator conditions, treatment fidelity, and process evaluation.  Steps to ensure scientific rigor, reproducibility, and transparency when implementing studies also will be addressed.",
                "typicallyOffered": "Fall",
            },
            "courseId": "097940",
            "courseOfferNumber": 1,
            "courseTopicId": 0,
            "effdt": 1690862400000,
            "inst": "IUBLA",
            "maxCredits": 3,
            "minCredits": 3,
            "scheduled": "",
            "scheduledTerms": [],
            "subject": "SPH-N",
            "title": "NUTRITION RESEARCH METHODS, RIGOR, REPRODUCIBILITY, AND TRANSPARENCY",
        },
    ],
    "filters": {
        "attributes": [
            {
                "active": False,
                "count": 1,
                "label": "Class uses IU eTexts",
                "value": "Class uses IU eTexts",
            },
            {
                "active": False,
                "count": 2,
                "label": "COLL (CASE) A&H Breadth of Inquiry credit",
                "value": "COLL (CASE) A&H Breadth of Inquiry credit",
            },
            {
                "active": False,
                "count": 2,
                "label": "IUB GenEd A&H credit",
                "value": "IUB GenEd A&H credit",
            },
        ],
        "level": [
            {"active": False, "count": 4, "label": "100", "value": "100"},
            {"active": False, "count": 1, "label": "200", "value": "200"},
            {"active": False, "count": 4, "label": "300", "value": "300"},
            {"active": False, "count": 1, "label": "500", "value": "500"},
            {"active": False, "count": 2, "label": "≥600", "value": "≥600"},
        ],
        "locations": [
            {
                "active": False,
                "count": 12,
                "label": "Bloomington Campus",
                "value": "Bloomington Campus",
            }
        ],
        "meetingTimes": "",
        "mois": [
            {
                "active": False,
                "count": 8,
                "label": "Distance Synchronous Video",
                "value": "Distance Synchronous Video",
            },
            {
                "active": False,
                "count": 17,
                "label": "Hybrid-Distance Video & Online",
                "value": "Hybrid-Distance Video & Online",
            },
            {
                "active": True,
                "count": 12,
                "label": "Hybrid-On Campus & Online",
                "value": "Hybrid-On Campus & Online",
            },
            {"active": False, "count": 217, "label": "In Person", "value": "In Person"},
            {
                "active": False,
                "count": 2,
                "label": "Independent/Directed Study",
                "value": "Independent/Directed Study",
            },
            {
                "active": False,
                "count": 2,
                "label": "Internship/Practica",
                "value": "Internship/Practica",
            },
        ],
        "sessions": [
            {
                "active": False,
                "count": 1,
                "label": "Eight Week - First",
                "value": "Eight Week - First",
            },
            {
                "active": False,
                "count": 2,
                "label": "Eight Week - Second",
                "value": "Eight Week - Second",
            },
            {
                "active": False,
                "count": 8,
                "label": "Regular Academic Session",
                "value": "Regular Academic Session",
            },
            {
                "active": False,
                "count": 1,
                "label": "Thirteen Week",
                "value": "Thirteen Week",
            },
        ],
        "subject": [
            {
                "active": False,
                "count": 2,
                "label": "College of Arts & Sciences",
                "value": "College of Arts & Sciences",
            },
            {"active": False, "count": 1, "label": "Education", "value": "Education"},
            {
                "active": False,
                "count": 3,
                "label": "Media School",
                "value": "Media School",
            },
            {"active": False, "count": 2, "label": "Nursing", "value": "Nursing"},
            {
                "active": False,
                "count": 4,
                "label": "Public Health",
                "value": "Public Health",
            },
        ],
        "units": [
            {"active": False, "count": 1, "label": "2", "value": "2"},
            {"active": False, "count": 11, "label": "3", "value": "3"},
        ],
    },
}


instructors_data = {
    "instructors": [
        "Amy C Wonder",
        "Andrea Lynn Tanner",
        "Ann Marie Huntoon",
        "Coy Timbrook",
        "Cydne Perry",
        "George H. Fowler",
        "Jeffrey A Keag",
        "Jiayao Qi",
        "Jill Evans",
        "Noble Reid Guyon",
        "Patrick Allen Dhaene",
        "Thomas A. Brush",
    ]
}


# instructor = instructor["instructors"]
# courses = courses["courses"]

# print(instructor[0])
# print(courses[0]["car"])

rows = []
for i in range(len(instructors_data["instructors"])):
    instr = instructors_data["instructors"][i]
    course = courses["courses"][i]

    rows.append(
        {
            "Semester": "Fall 2025",
            "Course Code": f"{course['subject']} {course['catalogNumber']}",
            "Course Title": course["title"],
            "Class Number": course["classNumbers"][
                0
            ],  # Taking the first class number in the list
            "Instructor Name": instr,
            "Enrolled Students": None,  # Leaving blank as it's missing from the current JSON
            "Credit Hours": course["maxCredits"],
        }
    )

print(rows)

df = pd.DataFrame(rows)
df.to_csv("university_schedule.csv", index=False)

print("File 'university_schedule.csv' has been created successfully!")
